name: tiger_development
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter:
    sdk: flutter
  get: ^4.7.2
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_intl:
  enabled: true
